### ISSUE TITLE
退出插入模式时， 等待几秒才会切换至英文

### ISSUE THREAD

**Issue by welandx** [xiaolulua/vim-awheel_fcitx#1]
Hi xiaolulua:
实际表现大概如下，我在多个系统下测试都是这个表现

![Peek 2022-01-07 22-38](https://user-images.githubusercontent.com/59045899/148559580-e01ba2a0-37c1-4f5e-8e48-6b927cbcf3e3.gif)

我不是很懂viml，所以无法发现什么地方导致了延迟

```
function! s:fcitx_2_english()
	let s:exit_insert_status = system(s:get_fcitx_language_status)      "检查退出 插入模式 时,输入法的状态
	if s:exit_insert_status != s:english_enable                         "如果退出 插入模式 时,输入法不是英文
		let l:temp = system(s:set_fcitx_english)                        "将输入法设置为英文
	endif
	let g:saved_insert_mode_language_status = s:exit_insert_status      "保存退出 插入模式 时的输入法状态 
endfunction
```
使用 **lua** 重写会解决这个问题吗？
希望能得到指点，感谢

from welandx

**Comment by welandx** [comment]
虽然不知道为什么，用lua重写之后就没有这个问题了

**Comment by xiaolulua** [comment]
这个是我原先使用ubuntu18.04和google拼音输入法搭配使用的
这个是有一个时间来控制的

**Comment by xiaolulua** [comment]
具体时间那个配置项我忘了是啥了 好久没有折腾vim了
